export const ADD_INGREDIENTS_TO_CART: 'ADD_INGREDIENTS_TO_CART' = 'ADD_INGREDIENTS_TO_CART'
export const DELETE_INGREDIENTS_FROM_CART: 'DELETE_INGREDIENTS_FROM_CART' = 'DELETE_INGREDIENTS_FROM_CART'
export const ADD_BUN_TO_CART: 'ADD_BUN_TO_CART' = 'ADD_BUN_TO_CART'

export const TOTAL_SUM_INGREDIENTS: 'TOTAL_SUM_INGREDIENTS' = 'TOTAL_SUM_INGREDIENTS'
export const TOTAL_SUM_BUN: 'TOTAL_SUM_BUN' = 'TOTAL_SUM_BUN'

export const UPDATE_INGREDIENTS_IN_CART: 'UPDATE_INGREDIENTS_IN_CART' = 'UPDATE_INGREDIENTS_IN_CART'
export const DELETE_ALL_INGREDIENTS_FROM_CART: 'DELETE_ALL_INGREDIENTS_FROM_CART' = 'DELETE_ALL_INGREDIENTS_FROM_CART'
